### ISSUE TITLE
cs_daemon panic

### ISSUE THREAD

**Issue by b0a7** [nodeset-org/hyperdrive-constellation#26]
I think it happened when I was restarting RocketPool eth1 to add a command line option.

hyperdrive_cs_daemon  | panic: runtime error: invalid memory address or nil pointer dereference
hyperdrive_cs_daemon  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe05edc]
hyperdrive_cs_daemon  |
hyperdrive_cs_daemon  | goroutine 53 [running]:
hyperdrive_cs_daemon  | github.com/rocket-pool/node-manager-core/node/services.runFunction1[...]({0x169c028, 0xc000810340}, {0x1695020, 0x20233e0}, 0xc000c83818)
hyperdrive_cs_daemon  |         /go/pkg/mod/github.com/rocket-pool/node-manager-core@v0.5.2-0.20241011014615-2cf2a45afa0a/node/services/function-runners.go:35 +0x37c
hyperdrive_cs_daemon  | github.com/rocket-pool/node-manager-core/node/services.(*ExecutionClientManager).CallContract(0x0?, {0x1695020?, 0x20233e0?}, {{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...}, ...)
hyperdrive_cs_daemon  |         /go/pkg/mod/github.com/rocket-pool/node-manager-core@v0.5.2-0.20241011014615-2cf2a45afa0a/node/services/ec-manager.go:104 +0x76
hyperdrive_cs_daemon  | github.com/rocket-pool/batch-query.(*MultiCaller).FlexibleCall(0xc00083b300, 0x1, 0x0)
hyperdrive_cs_daemon  |         /go/pkg/mod/github.com/rocket-pool/batch-query@v1.0.0/multicaller.go:140 +0x303
hyperdrive_cs_daemon  | github.com/rocket-pool/node-manager-core/eth.(*QueryManager).Query(0x0?, 0xc000dcdd28, 0x0, {0x0, 0x0, 0x0?})
hyperdrive_cs_daemon  |         /go/pkg/mod/github.com/rocket-pool/node-manager-core@v0.5.2-0.20241011014615-2cf2a45afa0a/eth/query-manager.go:57 +0x185
hyperdrive_cs_daemon  | github.com/rocket-pool/rocketpool-go/v2/rocketpool.(*RocketPool).Query(...)
hyperdrive_cs_daemon  |         /go/pkg/mod/github.com/nodeset-org/rocketpool-go/v2@v2.0.0-b2.0.20240731214747-81867bb8ff63/rocketpool/rocketpool.go:355
hyperdrive_cs_daemon  | github.com/rocket-pool/rocketpool-go/v2/rocketpool.(*RocketPool).GetProtocolVersion(0xc00056e620, 0x0)
hyperdrive_cs_daemon  |         /go/pkg/mod/github.com/nodeset-org/rocketpool-go/v2@v2.0.0-b2.0.20240731214747-81867bb8ff63/rocketpool/rocketpool.go:255 +0x9b
hyperdrive_cs_daemon  | github.com/nodeset-org/hyperdrive-constellation/common.(*RocketPoolManager).RefreshRocketPoolContracts(0xc0004b8e88)
hyperdrive_cs_daemon  |         /hyperdrive-constellation/common/rocket-pool-manager.go:46 +0x99
hyperdrive_cs_daemon  | github.com/nodeset-org/hyperdrive-constellation/tasks.(*NetworkSnapshotTask).refreshContracts(0xc0005306e0)
hyperdrive_cs_daemon  |         /hyperdrive-constellation/tasks/create-snapshot.go:94 +0x25
hyperdrive_cs_daemon  | github.com/nodeset-org/hyperdrive-constellation/tasks.(*NetworkSnapshotTask).Run(0xc0005306e0, 0xc000d7c000)
hyperdrive_cs_daemon  |         /hyperdrive-constellation/tasks/create-snapshot.go:73 +0x69
hyperdrive_cs_daemon  | github.com/nodeset-org/hyperdrive-constellation/tasks.(*TaskLoop).runTasks(0xc0007cfda0, 0xc000069e30?)
hyperdrive_cs_daemon  |         /hyperdrive-constellation/tasks/run.go:240 +0x25
hyperdrive_cs_daemon  | github.com/nodeset-org/hyperdrive-constellation/tasks.(*TaskLoop).Run.func1()
hyperdrive_cs_daemon  |         /hyperdrive-constellation/tasks/run.go:104 +0x78
hyperdrive_cs_daemon  | created by github.com/nodeset-org/hyperdrive-constellation/tasks.(*TaskLoop).Run in goroutine 1
hyperdrive_cs_daemon  |         /hyperdrive-constellation/tasks/run.go:90 +0x67
hyperdrive_cs_daemon exited with code 0

**Comment by b0a7** [comment]
$ hyperdrive s v

Hyperdrive is currently using the Ethereum Mainnet.

Hyperdrive:
CLI version: 1.1.0
Daemon version: 1.1.0
Selected Execution Client: Externally managed (Nethermind)
Selected Beacon Node: Externally managed (Nimbus)
MEV-Boost client: Enabled (External Mode)

Modules:
Constellation version: 1.0.0
